### ISSUE TITLE
java.lang.NoSuchMethodError: play.api.mvc.BodyParsers.parse

### ISSUE THREAD

**Issue by ikr0m** [kpmeen/clammyscan#19]
I'm using playframework 2.6.6.
From this thread https://groups.google.com/forum/#!topic/play-framework/vmLFEH80KYA playframework version 2.6.6 is not compatible with older versions. You already updated play version but haven't released it yet.
Can you please create a new release for this issue?

**Comment by kpmeen** [comment]
Hi @ikr0m 
I just published a version `1.1.0` compiled against play 2.6.6. Hope you're finding the library useful!

**Comment by ikr0m** [comment]
Hi @kpmeen! Thanks for fast release. 
This library is very useful!
